# Generated by Django 3.1 on 2020-08-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.PositiveIntegerField(default=0)),
                ('sum_of_rates', models.PositiveIntegerField(default=0)),
                ('make', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
